---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: generator
  labels:
    app: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      schedulerName: vineyard-scheduler
      containers:
      - name: nginx
        image: registry-vpc.cn-hongkong.aliyuncs.com/libvineyard/vineyardd:ubuntu
        command:
        - tail
        - -f
        resources:
          limits:
            cpu: 300m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 1024Mi
        volumeMounts:
        - mountPath: /tmp/vineyard
          name: vineyard
        - name: run
          mountPath: /var/run
        - name: shm
          mountPath: /dev/shm

      volumes:
      - name: vineyard
        emptyDir:
          medium: Memory
      - name: run
        hostPath:
          path: /var/run/vineyard
      - name: shm
        emptyDir:
          medium: Memory
