apiVersion: v1
kind: Service
metadata:
  name: nginx-rs-srv
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        scheduling.k8s.v6d.io/job: nginx
        scheduling.k8s.v6d.io/required: "a-b-c-d"
        scheduling.k8s.v6d.io/replica: "3"
    spec:
      schedulerName: vineyard-scheduler
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - mountPath: /tmp/vineyard
          name: vineyard
        - name: run
          mountPath: /var/run
        - name: shm
          mountPath: /dev/shm
      initContainers:
      - name: vineyard-migration
        image: registry-vpc.cn-hongkong.aliyuncs.com/libvineyard/vineyardd:ubuntu
        imagePullPolicy: Always
        command: ['sh', '-c']
        args:
        - /usr/local/bin/vineyard-migrate-to-local 3 ${MY_POD_NAME##*-} "a-b-c-d"
        volumeMounts:
        - mountPath: /tmp/vineyard
          name: vineyard
        - name: run
          mountPath: /var/run
        - name: shm
          mountPath: /dev/shm

      volumes:
      - name: vineyard
        emptyDir:
          medium: Memory
      - name: run
        hostPath:
          path: /var/run/vineyard
      - name: shm
        emptyDir:
          medium: Memory
